### ISSUE TITLE
Support for rbg(R G B / T) color notation

### ISSUE THREAD

**Issue by Razunter** [gilmoreorless/postcss-gradient-transparency-fix#61]
Currently, there is no support for modern rgb() and the plugin generates warnings, for example:
```css
a {
  background-image: linear-gradient(
    to top,
    rgb(0 0 0 / 0.6),
    10%,
    transparent,
    95%,
    rgb(0 0 0 / 0.3)
  );
}
```

This code causes
> Cannot calculate transparency for an invalid color. Please check your color stop definitions. [postcss-gradient-transparency-fix]

Same issue with `oklch(0.452 0.313 264.1)`
